### ISSUE TITLE
improve responsiveness of navbar

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#102]
## Current problems
- we should be able to easily support smaller laptop screens, but below 1100 px social icons disappear and below 1090 px, all of the top navigation elements except the brand disappear.
- At 843 px, the options button appears. This needs to be tuned with the above problems. 
- The taller nav brand also looks bad for various reasons at the 843px width, might have to mess with text, or change the brand itself.
- the options button actually has a taller height than the navbar itself, which becomes apparent at 843px as well; the nav probably just needs to be a bit thicker
- on clicking the options button, the dropdown it creates has problems of its own; the background is transparent for some reason on the individual elements, and the text disappears; everything is crowded. needs some TLC
- it might also be ideal to have some kind of label next to the options button after it appears at 843px to indicate that it is not just "options", but in fact the main navigational functionality of the site. So adding something like "Stages", "Process", whatever.

**Comment by sarahelizabeth** [comment]
The only thing I can't figure out how to do is place an opaque black background behind the menu options when they drop down. Also, the social icons don't show up until you hover over them and I can't figure out why, do you know @eads ? 
Other than those two things it's pretty much done.

**Comment by eads** [comment]
I will take a look. What's the inspector got to say?

**Comment by sarahelizabeth** [comment]
Never mind I think I figured it out for the most part actually. It doesn't
look precisely as I would like but close enough for now.

**Comment by sarahelizabeth** [comment]
Sorry I meant about the black background. I still can't figure out the social icons.

**Comment by bepetersn** [comment]
Where are all these changes right now? Anywhere I or Dave can pull from?
Merge you've merged by now.

**Comment by sarahelizabeth** [comment]
I just pushed again

**Comment by bepetersn** [comment]
OK, so I'm not the seeing the particular problem you were talking about. As long as the social icons are visible for me, they're clickable. However, I think they could be made to be visible at lower page width than they currently are. Same with the brand, maybe. See #104, maybe.

**Comment by sarahelizabeth** [comment]
Yes I have not merged them yet.
