### ISSUE TITLE
make the entire homepage overlay fade in together

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#112]
It looks weird right now, as only the title fades in, while the rest of the overlay doesn't. This will require some annoying pushing around of CSS, or changing of the element that actually gets faded.

**Comment by bepetersn** [comment]
@sarahelizabeth, did you say you had tried to make progress on this?

**Comment by sarahelizabeth** [comment]
Nope by all concepts of how this works, what I put in there should work. It
must be an issue with markdown...

**Comment by bepetersn** [comment]
Maybe it's just the annoying way we load the image and image wrapper in,
that's causing it.

On Tue, Mar 25, 2014 at 7:22 PM, Sarah notifications@github.com wrote:

> Nope by all concepts of how this works, what I put in there should work. It
> must be an issue with markdown...
> 
> On Tue, Mar 25, 2014 at 6:46 PM, Brian Everett Peterson <
> notifications@github.com> wrote:
> 
> > @sarahelizabeth https://github.com/sarahelizabeth, did you say you had
> > tried to make progress on this?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/chicago-justice/issues/112#issuecomment-38635389>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/112#issuecomment-38637649
> .

## 

Brian Peterson

**Comment by sarahelizabeth** [comment]
fixed
