### ISSUE TITLE
navbar dropdown is sticky below window width of 768

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#12]
With these small window widths, there is a problem of the dropdown bar being sticky after you click one of its elements. I don't know why, but it doesn't go back up after you select a dropdown element. Problem with my CSS?

**Comment by bepetersn** [comment]
@eads, @mmisery, @nwinklareth, what do you think of this?

**Comment by bepetersn** [comment]
I guess the way you're supposed to close the dropdown is by clicking the "hamburger" options menu thingy again. Doing so within the "slide.html" page has a visible effect, but the dropdown stays in place. 

It does not happen for any other page.

**Comment by eads** [comment]
Hey Brian, are you publishing this to a staging site somewhere? It might be
nice to see it in the wild.

On Mon, Dec 2, 2013 at 10:29 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> I guess the way you're supposed to close the dropdown is by clicking the
> "hamburger" options menu thingy again. Doing so within the "slide.html"
> page has a visible effect, but the dropdown stays in place.
> 
> It does not happen for any other page.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29632369
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by bepetersn** [comment]
Hey Dave, just sent an email out to Chris Whitaker about setting up an Amazon S3 bucket. But as of now I don't have the site to stage with.

**Comment by eads** [comment]
Just set one up yourself. It's free. Or I can set one up for you in my AWS
account.

On Mon, Dec 2, 2013 at 10:59 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> Hey Dave, just sent an email out to Chris Whitaker about setting up an
> Amazon S3 bucket. But as of now I don't have the site to stage with.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29635739
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eads** [comment]
Do they give you access to create S3 buckets?

On Mon, Dec 2, 2013 at 11:19 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> Chris points me to:
> 
> http://www.smartchicagocollaborative.org/projects/hosted-web-space/
> 
> On Mon, Dec 2, 2013 at 11:00 AM, David Eads notifications@github.comwrote:
> 
> > Just set one up yourself. It's free. Or I can set one up for you in my
> > AWS
> > account.
> > 
> > On Mon, Dec 2, 2013 at 10:59 AM, Brian Everett Peterson <
> > notifications@github.com> wrote:
> > 
> > > Hey Dave, just sent an email out to Chris Whitaker about setting up an
> > > Amazon S3 bucket. But as of now I don't have the site to stage with.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29635739>
> > 
> > > .
> > 
> > ## 
> > 
> > David Eads - 773.354.2285
> > News applications developer, Chicago Tribune (
> > http://www.chicagotribune.com/news/data/)
> > Founder, FreeGeek Chicago (http://freegeekchicago.org)
> > 
> > "Medical statistics will be our standard of measurement: we will weigh
> > life
> > for life and see where the dead lie thicker, among the workers or among
> > the
> > privileged." -- Rudolf Virchow
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29635802>
> > 
> > .
> 
> ## 
> 
> Brian Peterson
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29637614
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by bepetersn** [comment]
I believe they're going to, but I may not be able to get up a public site
'til later today.

On Mon, Dec 2, 2013 at 11:35 AM, David Eads notifications@github.comwrote:

> Do they give you access to create S3 buckets?
> 
> On Mon, Dec 2, 2013 at 11:19 AM, Brian Everett Peterson <
> notifications@github.com> wrote:
> 
> > Chris points me to:
> > 
> > http://www.smartchicagocollaborative.org/projects/hosted-web-space/
> > 
> > On Mon, Dec 2, 2013 at 11:00 AM, David Eads notifications@github.comwrote:
> > 
> > > Just set one up yourself. It's free. Or I can set one up for you in my
> > > AWS
> > > account.
> > > 
> > > On Mon, Dec 2, 2013 at 10:59 AM, Brian Everett Peterson <
> > > notifications@github.com> wrote:
> > > 
> > > > Hey Dave, just sent an email out to Chris Whitaker about setting up
> > > > an
> > > > Amazon S3 bucket. But as of now I don't have the site to stage with.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29635739>
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > David Eads - 773.354.2285
> > > News applications developer, Chicago Tribune (
> > > http://www.chicagotribune.com/news/data/)
> > > Founder, FreeGeek Chicago (http://freegeekchicago.org)
> > > 
> > > "Medical statistics will be our standard of measurement: we will weigh
> > > life
> > > for life and see where the dead lie thicker, among the workers or
> > > among
> > > the
> > > privileged." -- Rudolf Virchow
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29635802>
> > 
> > > .
> > 
> > ## 
> > 
> > Brian Peterson
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29637614>
> > 
> > .
> 
> ## 
> 
> David Eads - 773.354.2285
> News applications developer, Chicago Tribune (
> http://www.chicagotribune.com/news/data/)
> Founder, FreeGeek Chicago (http://freegeekchicago.org)
> 
> "Medical statistics will be our standard of measurement: we will weigh
> life
> for life and see where the dead lie thicker, among the workers or among
> the
> privileged." -- Rudolf Virchow
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29639040
> .

## 

Brian Peterson

**Comment by MMisery** [comment]
I'll try to give it a look-over at some point. I need to handle some publickey errors I've been getting with the project.

**Comment by bepetersn** [comment]
Public key... errors?

On Tue, Dec 3, 2013 at 4:50 PM, MMisery notifications@github.com wrote:

> I'll try to give it a look-over at some point. I need to handle some
> publickey errors I've been getting with the project.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29760087
> .

## 

Brian Peterson

**Comment by bepetersn** [comment]
Matt, did you mean with this project? Or some other project?

**Comment by MMisery** [comment]
Yeah, it was with this project. I've found some solutions to general publickey errors - I just have to try to implement them.

**Comment by eads** [comment]
Can you explain these problems? I'm baffled.

**Comment by bepetersn** [comment]
Did you have trouble pulling/pushing? Can't you elaborate?

**Comment by MMisery** [comment]
Right. It's a "Permission denied (publickey)" error thrown when cloning the repo (git clone git@github.com:bepetersn/chicago-justice.git). I'm going to be trying the solution offered at https://help.github.com/articles/error-permission-denied-publickey.

**Comment by MMisery** [comment]
Alright, so my problem's done. I didn't have an SSH key for my virtual environment, so I had to go through the steps listed at the link listed above and at https://help.github.com/articles/generating-ssh-keys. Key was created and then added to account. Cloned the repo and started the server, though it was pretty slow in starting. Now we can all move to the main problem.

**Comment by MMisery** [comment]
So, something I've noticed that may or may not be playing a part in all this (and it may just be me): the links in the navbar. I haven't seen where the links are set up, but if you hover over the links in navbar, each name is prepended by "#", so the link doesn't go anywhere. 

If you check the example at http://getbootstrap.com/examples/carousel/ with a phone screen sized browser window, you'll see that, when you expand the navbar and click on a link, the menu stays extended. You'll also notice that the link names are prepended with "#".

Messing with it is another issue, though. Still working on that.

**Comment by MMisery** [comment]
Yeah, so in your "_nav.html" file (not the one under _base), just change the "a href" tags from "#[name]" to "[name].html", i.e., "jail.html", "call.html", etc. After that, clicking on the link should go to the actual page and throw the command to collapse the navbar (it's a JavaScript thing). All in all, it's mostly just an HTML issue.

**Comment by bepetersn** [comment]
I'm not sure I follow. If you see how the routing is actually done, you'll
see that it doesn't redirect to a new page when you click the next and
previous buttons, or when you click the nav buttons. Instead, I do an AJAX
call and pull the html of the other pages into the current one.

It's not really well done right now... I am thinking re-doing the lion's
share of the routing functionality.

On Wed, Dec 4, 2013 at 11:39 PM, MMisery notifications@github.com wrote:

> Yeah, so in your "_nav.html" file (not the one under _base), just change
> the "a href" tags from "#[name]" to "[name].html", i.e., "jail.html",
> "call.html", etc. After that, clicking on the link should go to the actual
> page and throw the command to collapse the navbar (it's a JavaScript thing).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29872983
> .

## 

Brian Peterson

**Comment by bepetersn** [comment]
For instance, navigating to #call sets off an onHashChange event listener,
which takes the value of the hash and tries to pull in an html page of the
same name.

As I said, it's a bit wonky, but the nav isn't intended to point to
call.html.

On Thu, Dec 5, 2013 at 12:48 AM, Brian Peterson bepetersn@gmail.com wrote:

> I'm not sure I follow. If you see how the routing is actually done, you'll
> see that it doesn't redirect to a new page when you click the next and
> previous buttons, or when you click the nav buttons. Instead, I do an AJAX
> call and pull the html of the other pages into the current one.
> 
> It's not really well done right now... I am thinking re-doing the lion's
> share of the routing functionality.
> 
> On Wed, Dec 4, 2013 at 11:39 PM, MMisery notifications@github.com wrote:
> 
> > Yeah, so in your "_nav.html" file (not the one under _base), just change
> > the "a href" tags from "#[name]" to "[name].html", i.e., "jail.html",
> > "call.html", etc. After that, clicking on the link should go to the actual
> > page and throw the command to collapse the navbar (it's a JavaScript thing).
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29872983
> > .
> 
> ## 
> 
> Brian Peterson

## 

Brian Peterson

**Comment by bepetersn** [comment]
For instance, navigating to #call sets off an onHashChange event listener,
which takes the value of the hash and tries to pull in an html page of the
same name. As I said, it's a bit wonky, but the nav isn't intended to point
to call.html.

But this could still be causing the messed up functionality I'm seeing. As
it happens, I just remembered something probably important: there was a
point at which I broke a whole bunch of the routing functionality. For the
pages for which it failed, the nav held the highlighted style as expected.
For the (one) working page, it wouldn't hold the style.

On Thu, Dec 5, 2013 at 12:48 AM, Brian Peterson bepetersn@gmail.com wrote:

> I'm not sure I follow. If you see how the routing is actually done, you'll
> see that it doesn't redirect to a new page when you click the next and
> previous buttons, or when you click the nav buttons. Instead, I do an AJAX
> call and pull the html of the other pages into the current one.
> 
> It's not really well done right now... I am thinking re-doing the lion's
> share of the routing functionality.
> 
> On Wed, Dec 4, 2013 at 11:39 PM, MMisery notifications@github.com wrote:
> 
> > Yeah, so in your "_nav.html" file (not the one under _base), just change
> > the "a href" tags from "#[name]" to "[name].html", i.e., "jail.html",
> > "call.html", etc. After that, clicking on the link should go to the actual
> > page and throw the command to collapse the navbar (it's a JavaScript thing).
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29872983
> > .
> 
> ## 
> 
> Brian Peterson

## 

Brian Peterson

**Comment by MMisery** [comment]
Ah. I get you. I hadn't been testing it from slide.html - just the pages themselves. So, although the solution I posted helps with the nav issue, it doesn't go with the routing as you intend it.

Back to the drawing board.

**Comment by bepetersn** [comment]
Well, in a sense your solution is the correct one, and my routing wrong.
But from the reverse perspective its the reverse, lol. I'm gonna reform the
whole thing, don't worry.

On Thu, Dec 5, 2013 at 1:45 AM, MMisery notifications@github.com wrote:

> Ah. I get you. I hadn't been testing it from slide.html - just the pages
> themselves. So, although the solution I posted helps with the nav issue, it
> doesn't go with the routing as you intend it.
> 
> Back to the drawing board.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/12#issuecomment-29877464
> .

## 

Brian Peterson

**Comment by bepetersn** [comment]
Need to check if this is still an issue with the newest version.
