### ISSUE TITLE
make nav brand visible at mobile viewport (and between that and laptop, if possible)

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#121]
This is the easiest way to access the home page (as opposed to tabbing through to the beginning or end of the stages), and it definitely can fit after we move all the tabs into the options button.

**Comment by sarahelizabeth** [comment]
What if I just add an "Overview" tab to the top of the options menu.... somehow....

**Comment by bepetersn** [comment]
Somehow...

On Mon, Mar 24, 2014 at 6:56 PM, Sarah notifications@github.com wrote:

> What if I just add an "Overview" tab to the top of the options menu....
> somehow....
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/121#issuecomment-38516412
> .

## 

Brian Peterson

**Comment by sarahelizabeth** [comment]
I figured it out. Closing this.
