### ISSUE TITLE
Make it clear that the options button at mobile viewport is important

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#122]
Having a thing that says "Process" or "Stages", or something like that is what I had in mind. @eads once suggested this, I believe.

**Comment by sarahelizabeth** [comment]
Done, do we like this?
![screen shot 2014-03-24 at 8 31 23 pm](https://f.cloud.github.com/assets/4665373/2507470/6354c2c0-b3bd-11e3-98a8-41883e0a0240.png)

**Comment by bepetersn** [comment]
Yes! Love it.
