### ISSUE TITLE
on mobile, page footer covers up some text at the bottom of the page

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#139]
This happens on many but not all of the pages; specifically: Incidents, Arrest, Court and Prison

**Comment by bepetersn** [comment]
I tried just adding some page breaks, e.g. "<br <br", to the bottom of these pages, but it didn't work. We need to include some css margins or something, to get the job done.

**Comment by sarahelizabeth** [comment]
added 3% padding to container div

**Comment by eads** [comment]
Put a 50 or 100px bottom padding on the bottom.
