### ISSUE TITLE
Change URL - Top Domain? 

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#156]
Is chicago-justice.smartchicagoapps.org an ok URL as we have the title on the site as "Crime and Punishment in Chicago" ? 

We can use a top-level domain like crimeandpunishmentchicago.org OR we can do something like crime.smartchicagoapps.org or justice.smartchicagoapps.org 

@Danxoneil, @srobbin - What do you think?

**Comment by srobbin** [comment]
I like either crimeandpunishmentchicago.org or justice.smartchicagoapps.org

**Comment by GovInTrenches** [comment]
@srobbin 

We're going to go with crime-punishment.smartchicagoapps.org as our final answer. Can you update the URL? 

Thanks a ton, @govintrenches
