### ISSUE TITLE
Add more links to other examples, not just best practices

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#164]
Add links to other agencies that release data and not just the best.

**Comment by bepetersn** [comment]
This has research and writing aspects, as well as design and coding aspects. In order to expedite the process of getting it done, it might make sense to break it up into multiple tickets, once we get clear on what needs to be done.

In terms of research, the last time that this was brought up, @tjakester seemed to think it was a very large task, and that there are possibly too many agencies in too many places to try to cover. This implies we have to come up with some basic criteria for what makes a particular agency worth listing, among the many that there are.

In terms of design, we could try to bring back some expand-collapse javascript in order to make this happen. I had a [different javascript plugin](http://www.adipalaz.com/experiments/jquery/everything_expanded.html) in mind than our old one to make this work in a less buggy and more user-friendly way. 

In terms of storing these lists / copy, we're probably going to do a little bit of engineering of some macros to get this done.

**Comment by tjakester** [comment]
Hello,

Here is the google doc Dan and I have been working on.  It lists all of the agencies that i have been able to locate that release data.  I think Dan was thinking more of just a list of agencies with links.  These are all that I was able to find.  It does not mean that this is all that there are.  The are 19,000 police agencies in the US and probably thousands of courts and prosecutor’s offices.  This is probably but a taste of what is truly available throughout the country.  It would take months to find them all.  This should suffice for this project. 

https://docs.google.com/document/d/1kU8PnOzcbJsWIIq8fy-HPji1PMDqjRqBUa3RbCRi48E/edit#

Let me know what are thinking in terms of written content.  Probably very short with some sort of list or drop down.

Tracy

On Mar 30, 2014, at 5:05 PM, Brian Everett Peterson notifications@github.com wrote:

> This has research and writing aspects, as well as design and coding aspects. In order to expedite the process of getting it done, it might make sense to break it up into multiple tickets, once we get clear on what needs to be done.
> 
> In terms of research, the last time that this was brought up, @tjakester seemed to think it was a very large task, and that there are possibly too many agencies in too many places to try to cover. This implies we have to come up with some basic criteria for what makes a particular agency worth listing, among the many that there are.
> 
> In terms of design, we could try to bring back some expand-collapse javascript in order to make this happen. I had a different javascript plugin in mind than our old one to make this work in a less buggy and more user-friendly way.
> 
> In terms of storing these lists / copy, we're probably going to do a little bit of engineering of some macros to get this done.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Tracy Siska | Executive Director
Chicago Justice Project | 35 E. Wacker Drive, 9th Floor | Chicago, IL 60601
Ph. (312) 564 – 5685 | Fax (312) 376 - 0162

tsiska@chicagojustice.org | www.chicagojustice.org
Twitter: CJPJustProj | Facebook: Become a Fan

**Comment by GovInTrenches** [comment]
I’m currently adding the list now. Brian will see them as a crapton of pull requests on my end. 

-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On March 31, 2014 at 3:15:11 PM, tjakester (notifications@github.com) wrote:

Hello,

Here is the google doc Dan and I have been working on. It lists all of the agencies that i have been able to locate that release data. I think Dan was thinking more of just a list of agencies with links. These are all that I was able to find. It does not mean that this is all that there are. The are 19,000 police agencies in the US and probably thousands of courts and prosecutor’s offices. This is probably but a taste of what is truly available throughout the country. It would take months to find them all. This should suffice for this project.

https://docs.google.com/document/d/1kU8PnOzcbJsWIIq8fy-HPji1PMDqjRqBUa3RbCRi48E/edit#

Let me know what are thinking in terms of written content. Probably very short with some sort of list or drop down.

Tracy

On Mar 30, 2014, at 5:05 PM, Brian Everett Peterson notifications@github.com wrote:

> This has research and writing aspects, as well as design and coding aspects. In order to expedite the process of getting it done, it might make sense to break it up into multiple tickets, once we get clear on what needs to be done.
> 
> In terms of research, the last time that this was brought up, @tjakester seemed to think it was a very large task, and that there are possibly too many agencies in too many places to try to cover. This implies we have to come up with some basic criteria for what makes a particular agency worth listing, among the many that there are.
> 
> In terms of design, we could try to bring back some expand-collapse javascript in order to make this happen. I had a different javascript plugin in mind than our old one to make this work in a less buggy and more user-friendly way.
> 
> In terms of storing these lists / copy, we're probably going to do a little bit of engineering of some macros to get this done.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Tracy Siska | Executive Director
Chicago Justice Project | 35 E. Wacker Drive, 9th Floor | Chicago, IL 60601
Ph. (312) 564 – 5685 | Fax (312) 376 - 0162

tsiska@chicagojustice.org | www.chicagojustice.org
Twitter: CJPJustProj | Facebook: Become a Fan
