### ISSUE TITLE
do user testing with SmartChicago

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#173]

**Comment by bepetersn** [comment]
Don't know what's going to be involved in this process.

**Comment by GovInTrenches** [comment]
Once we get the site launched, we’ll go into user testing. I’ll set that up with Sonja on a separate thread. 
-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On March 30, 2014 at 5:49:43 PM, Brian Everett Peterson (notifications@github.com) wrote:

Don't know what's going to be involved in this process.
