### ISSUE TITLE
new contributors get a 403 google drive error when running the server

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#24]
Perhaps the issue is that my tarbell_config.py file is loaded in with the project? 

@wilbertom and possibly @boboTjones reported seeing this error.

**Comment by bepetersn** [comment]
@eads, any initial thoughts?

**Comment by bepetersn** [comment]
It seems it is most likely permission issues with the google spreadsheet. I tried setting view permissions on the spreadsheet to public.

Can either of you guys, @wilbertom or @boboTjones confirm that you can start the server now?

**Comment by wilbertom** [comment]
Yeah I was getting those errors but now it's working. I tried a couple of things yesterday, don't know how I fixed it because when taking off what I thought helped, it continued to work.

**Comment by wilbertom** [comment]
@bepetersn  let's coordinate so you can un`share` the document with me for 30 minutes to see if it was that.

**Comment by bepetersn** [comment]
Note that I did share the spreadsheet with you, and then I made it public. It was definitely the permissions on the spreadsheet at any rate.

**Comment by bepetersn** [comment]
I think this has been fixed. We either have to have our spreadsheet public, or tell people to request access to it in the README.

For now, the latter works.
