### ISSUE TITLE
error when trying to explicitly navigate to a sub-page

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#25]
Navigating to "#project", works. 

Navigating to "#project/1", or any subpage, fails.

I suspect that a call to `<collection>.findWhere()` is returning undefined, but I'm not sure.

**Comment by bepetersn** [comment]
@wilbertom, you wanna take this one? Don't seem to be able to assign you. 

EDIT: 

Never mind, got it done.

EDIT EDIT: 

I successfully assigned the task, I didn't do the task.

**Comment by bepetersn** [comment]
This is now the most important task.

**Comment by wilbertom** [comment]
Is this done? If not I can take a crack at it.

**Comment by bepetersn** [comment]
Please do.
