### ISSUE TITLE
Refactor such that all subpages of a stage into a single html file

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#26]
I was the one who separated out the slides into their own individual pages in the first place, and it was for convenience's sake at the time, but it's pretty annoying to have that many files.

Besides copy-pasting html, in order to make this change but still load in the slides correctly, it will be necessary to do some work with jquery, based on stage and section:
- first $.get() the stage's template
- convert its html to a jquery-manipulable dom object
- select within the jquery object the correct sub-stage
- put the resulting html where it belongs

**Comment by bepetersn** [comment]
Maybe we don't need to do this right now. The app will work as is, so perhaps content / design / QA is of greater importance at this stage.

**Comment by wilbertom** [comment]
I think this can help. It would centralize the logic and make it easier to work.

**Comment by eads** [comment]
Yeah. Having separate files is problematic. The section part feels like
over engineering to me.

**Comment by bepetersn** [comment]
Wil is trying to move it all into underscore templating, now.

**Comment by eads** [comment]
Oi vey. Keep it simple homiez.

**Comment by wilbertom** [comment]
Hey guys, I have these changes on my master branch. I notice the change is pretty radical so I want to push them to a new branch. I just wasted an hour trying to and I'm scare to messup the project. Need help!

**Comment by eads** [comment]
fork, add a new remote to point to your fork, and push to that

On Sun, Dec 8, 2013 at 4:25 PM, Wilberto Morales
notifications@github.comwrote:

> Hey guys, I have these changes on my master branch. I notice the change is
> pretty radical so I want to push them to a new branch. I just wasted an
> hour trying to and I'm scare to messup the project. Need help!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bepetersn/chicago-justice/issues/26#issuecomment-30094739
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by wilbertom** [comment]
Thank you @eads  and @bepetersn. It might not be the best way so I can change it to another server side method

**Comment by bepetersn** [comment]
Here's the pull Wil made: https://github.com/bepetersn/chicago-justice/pull/30

**Comment by bepetersn** [comment]
Oh, also, someone made a jquery plugin for doing exactly what we had to do a whole bunch to accomplish:

https://github.com/defunkt/jquery-pjax
