### ISSUE TITLE
add license to this project

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#28]
I don't know which one. Someone choose.

**Comment by wilbertom** [comment]
The party you are making this for should pick.

**Comment by eads** [comment]
+1 Wilberto. For the moment the license should just be copyright the
client.

**Comment by GovInTrenches** [comment]
Smart Chicago uses the Creative Commons Attribution 3.0 Unported (CC BY 3.0) license on all of our work.

**Comment by danxoneil** [comment]
Yep @bepetersn @wilbertom @eads (CC BY 3.0) is the license.

**Comment by bepetersn** [comment]
fixed by @wilbertom with #71.
