### ISSUE TITLE
write css code that tells each slide how to interact with its featured image 

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#41]
Currently, the order that html is loaded into the slider primarily determines how things show up on a given slide. 

Ideally, we'd have pre-styled the elements in a given slide to work nice together, so that when they get loaded in, it just works.

This basically has to be done on a per-slide basis, and so is contingent on the content being loaded into the website.

**Comment by eads** [comment]
So 1) use imgliquid for all your image sizing needs. 2) You're right this
depends on content. Depending on how you set it up, you can probably
position and style the caption using the google spreadsheet.

**Comment by bepetersn** [comment]
Do you really think position and style of captions should be done in spreadsheet? I guess you did that with Finding Care...

**Comment by GovInTrenches** [comment]
I like the way that the Finding Care was overlaid. If we are doing a picture/content pattern, I'd rather be able just to scroll all the way down (vis a vis http://tarbell.tribapps.com/#) When it's configued like Finding Care, (Content over image) I don't mind the click-to-next as much.

**Comment by bepetersn** [comment]
This issue itself is mostly resolved thanks to @eads's help awhile back using imgliquid.

@GovInTrenches: in terms of navigation, would paddles on the side of each page that slide up and down with the page be any better than the "back" and "next" buttons at the bottom of the page that we've since removed? That might fit better with our current content structure, and is still the best solution I can think of.

**Comment by GovInTrenches** [comment]
I'd prefer the paddles actually - would give it more of a flow. Sounds good to me

Christopher Whitaker
(Sent from iPhone)
