### ISSUE TITLE
More resource based, not as much editorial 

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#46]
This should be more list of resources and less narrative based. We want to focus on what data is available, how it gets generated, and where the gaps are. 

Also, there _is_ transparency in many parts of the system - we can't editorialize too much, but rather say what is and isn't there. We'll let people form their own opinion if it's transparent or not.

**Comment by bepetersn** [comment]
Moving more in this direction, thanks to @GovInTrenches's suggestions.
