### ISSUE TITLE
Chicago-centric pictures

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#47]
I like the picture of the operator on the "Reporting/Call for Service" but we should be using Chicago pictures whenever possible. Dan has several thousands of pics on his http://www.flickr.com/photos/juggernautco/ page that we can pull from. 

Steve Vance also has some good photos such as this one:

http://www.flickr.com/photos/75698896@N00/6205528816/in/photolist-asmXw9-dFXx8w-dEHWWu-e9WfKo-azrPsF-e9QzYc-azrPpz-dduBED-e6xfAC-aqtFUA-aqFXAY-7DBJy6-ekkB35-fJ6xQV-cDGoqN-cDGBHG-7z75tJ-9SU6xn-aEtHzC-aEtBLy-aEu8Aq-8M2D9u-9JrumU-bqqxiT-9j2g5C-9j2fqY-7DFweY-8kX9rE

**Comment by bepetersn** [comment]
@GovInTrenches, do you have any more thoughts/plans about finding a picture of Chicago's call center, like you mentioned the other day?
