### ISSUE TITLE
Link to Raw Data

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#48]
As we gather up a list of all the different sets of data and the resources, we should make the raw data available for download.

**Comment by bepetersn** [comment]
We have yet to set up links pointing to all the FOIA'ed data; however, is having the data on our site actually necessary, or is linking to the Chicago Justice Project's copy of it enough, do you think?

**Comment by GovInTrenches** [comment]
I'm OK with Links - so long as we give it some context we should be good to link 

Christopher Whitaker
(Sent from iPhone)

**Comment by bepetersn** [comment]
Still don't have links up on the site to the successful FOIAs that Tracy's org has done.

**Comment by bepetersn** [comment]
I've just added the CJP's FOIA request for "Call for Service" data. @tjakester, are there any other relevant datasets that we should link to?

**Comment by tjakester** [comment]
this link here will have 5 years of cook county court conviction data once David finishes cleaning up the addresses.  Should be done before release.

Tracy

## 

Tracy Siska | Executive Director
Chicago Justice Project | 35 E. Wacker Drive, 9th Floor | Chicago, IL 60601
Ph. (312) 564 – 5685 | Fax (312) 376 - 0162

tsiska@chicagojustice.org | www.chicagojustice.org
Twitter: CJPJustProj | Facebook: Become a Fan

**Comment by tjakester** [comment]
this link here will have 5 years of cook county court conviction data once David finishes cleaning up the addresses.  Should be done before release.

http://www.chicagojustice.org/foi/data-sets-available-for-download/cook-county-court-data

Tracy

## 

Tracy Siska | Executive Director
Chicago Justice Project | 35 E. Wacker Drive, 9th Floor | Chicago, IL 60601
Ph. (312) 564 – 5685 | Fax (312) 376 - 0162

tsiska@chicagojustice.org | www.chicagojustice.org
Twitter: CJPJustProj | Facebook: Become a Fan

**Comment by bepetersn** [comment]
Added your link, pre-emptively. 

@tjakester, I had a related question that I think you can clear up. Currently on the "Call for Service" page, we list three fields as part of "Open Data". Is this out of date / wrong? Or, where is this data available? These are the fields I'm referring to: 
- If a report is written
- RD #
- Final coded clearance by the officer (this should tell OEMC if a report was written and for what crime type)

**Comment by tjakester** [comment]
The only fields open currently are:

Police event type
district

These two fields make up the data available on our site.  The rest of the fields in the attached excel doc are either FOIA able or not availble.  They are marked accordingly in the attached document.  What is up online currently does not list the Not available data. 

Tracy

## 

Tracy Siska | Executive Director
Chicago Justice Project | 35 E. Wacker Drive, 9th Floor | Chicago, IL 60601
Ph. (312) 564 – 5685 | Fax (312) 376 - 0162

tsiska@chicagojustice.org | www.chicagojustice.org
Twitter: CJPJustProj | Facebook: Become a Fan

**Comment by bepetersn** [comment]
Well, anyway, I guess I'll close this issue.
