### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#49]
The About Page will have information about: 

The Project itself 

The Partners 
- Smart Chicago
- FreeGeek Chicago
- Chicago Justice Project 

Open Source Link 

Raw Data Link 

Use this as an example: http://chicagohealthatlas.org/about

**Comment by bepetersn** [comment]
As of right now, my understanding (that others share, unless I'm wrong) is that we want to have much/most of this information on our landing page, underneath the landing page photo. This may change. This is my current idea of our plans, and besides navigational issues, is probably one of the most important next TO-DO items.

**Comment by GovInTrenches** [comment]
Correct - the landing page would be the about page

Christopher Whitaker
(Sent from iPhone)
