### ISSUE TITLE
"See More" Dropdown Content

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#51]
For the content that is going to be rather long, we'd like to have the option to put the content in a 'see more' dialog so that we can expand it. This would avoid scrolling forever in a day.

**Comment by bepetersn** [comment]
Still working on this -- @wilbertom had some idea of how to go about it, we might just have to play around a bit with it before we're satisfied, but we should have SOMETHING for this soon.

**Comment by sarahelizabeth** [comment]
Done as of last merge, did this with jQuery

**Comment by bepetersn** [comment]
Excellent!

**Comment by bepetersn** [comment]
Sarah, I'm seeing 404s like you described, for the jquery plugin I assume you added, "jquery-expander". In fact, there's a new folder in the "js" directory, but there's no actual new javascript added. Did you forget to add it in?

**Comment by bepetersn** [comment]
I was able to successfully add the jquery-expander to the js folder. I'm
about to commit the few changes needed to get to this point. A few snags
came up, though; here's the reasons why I reopened this issue:
- I see that you only added the "read more" component to a few pages, and
  not all. I would start adding it to more of the pages, but...
- The outer expandable div element you added seems to mess with the
  markdown rendering correctly inside of it. Specifically, the HTML that
  markdown outputs doesn't end up as list elements like it used to, but
  instead as a series of span tags each containing the one after it. THIS
  indicates that the hacky solution we were using before with the "<span
  class="available>" without closing the span, etc., is not going to hold up
  here. I'm still hoping there's an easy way around this particular problem,
  like if we get rid of these unnecessary spans.
- Actually, the features of this particular plugin may not be suited for
  our purpose of collapsing lists of fields. Take a look [here](http://www.adipalaz.com/experiments/jquery/expandAll_alternative_use.html)
  for something that might suit better. The feature I like about this one is
  that you don't have to scroll down to close a very long expanded section.

On Mon, Mar 17, 2014 at 2:23 PM, Brian Peterson bepetersn@gmail.com wrote:

> Excellent!
> On Mar 17, 2014 2:20 PM, "Sarah" notifications@github.com wrote:
> 
> > Done as of last merge, did this with jQuery
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/51#issuecomment-37858590
> > .

## 

Brian Peterson

**Comment by sarahelizabeth** [comment]
Why did you send me like 15 emails in triplicate....? Anyway, I only added it to a few pages because it only needs to be on a few pages. Consistency is one thing but overkill is also a thing.

**Comment by bepetersn** [comment]
Sorry for the emails, I didn't realize you'd get one for each edit. 

## 

To reiterate, it seems like this jquery plugin puts everything inside the expander div in quotes, which causes markdown to not render it. We may have to encode these lists of data fields into the page in pure html, else they will show up as a block of text with a bunch of "*" or "-" in between the words. That, or use a different plugin that works in a different way behind the scenes, if possible (could write the javascript ourselves).

I'm going to try to get #75 or something similar done tonight, as this would allow us to hardcode the HTML without mucking up the markdown. We might need a different bit of javascript anyway in the end to fulfill this "expanding" function, but odds are it would have similar issues with messing up markdown rendering.
