### ISSUE TITLE
Finish Victimization tab

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#54]
A tab on victimization to showcase data on victimization data. 

This is not a pitch-fork type issue, this is a human condition project. We need to make sure the site is focused on humans.

**Comment by bepetersn** [comment]
Can you provide links to this data? Tracy talked about this data quite awhile back, but from what I recall there was only federal-level data, and none for Chicago. Is that correct?

**Comment by danxoneil** [comment]
This is going to be more about text than data. I want to rely on Tracy Siska quite a bit, but it will go something like this:

All over Chicago, every day, in every corner of our oblong city, people commit crimes. This project seeks to index the data that document these crimes. We cover the collection of the voice of victims when they call 311, the daily notes of detectives who investigate crime, the material delivered to the court system when charges are filed, the records generated when convicts arrive in prison, and so on.

The documentation is immense. Some is published. Much of it is not. Our goal is to create a flat simple guide to what is known and what is not.

In each instance, this documentation process begins with a crime and ends with a dead end. That dead end could be a crime that goes unsolved, or a conviction, or dropped charges. 

But the first dead end is the crime that goes unreported and undetected. There is no data around this, but there are formulas that estimate the amount of unreported crime [TRACY].

**Comment by bepetersn** [comment]
See #57 and comments for some idea of the different parts of the site's components that you have to update to add a new tab.

**Comment by bepetersn** [comment]
This is what the summary should look like for the "Victimize" tab for now:

This is the occurrence of an event that may be considered a crime. Typically one of two things happen after an event occurs: It may be reported via 911 or directly discovered by the police (“on view”), or it go completely unreported and unnoticed. If it is reported, a Call for Service is created. If it is unreported, there is no further action and no further data, save for the uncollected journal entries, phone calls to friends, or gossip on tech blogs about insider trading.

**Comment by sarahelizabeth** [comment]
added .html page, summary content, two markdown files, and made everything point in the right direction but it is still coming up with a different title. @bepetersn 

@GovInTrenches Do you have an idea of what kind of photo you would like for this?
