### ISSUE TITLE
Change Nav tab from Report to Call for Service

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#55]
Better describes what's actually happening

**Comment by danxoneil** [comment]
Content for this section is here: https://docs.google.com/document/d/1kU8PnOzcbJsWIIq8fy-HPji1PMDqjRqBUa3RbCRi48E/edit#heading=h.xl0xrh25kd3q

**Comment by bepetersn** [comment]
See #57 for procedure to updating tab names. For the time being, it's the best I can do in terms of showing how it's done. Soon, ideally, it will be getting a lot easier to add new data / tabs to the site, so that the site can be maintained after this initial development.
