### ISSUE TITLE
Change Investigate to Incidents

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#57]

**Comment by wilbertom** [comment]
On the `investigate` tab? Including the chart? This can be changed easily.

**Comment by bepetersn** [comment]
Changing the names of our "stages" has to be done in a ridiculous number of places if
you want to be consistent and not confuse yourself later. Let me see if I
can recall them all, might as well try to document it:

1) in the spreadsheet, on sheet "stages"

2) optionally, in the "featured_image" name which the "stages" sheet
references

3) also, in a third place in the "stages" sheet, it may be necessary to rename the stage "headline", to better fit the new short-name.

4) optionally, in the filename for the image which the "stages" sheet
will point to, e.g. "investigate.jpg"

5) in the spreadsheet, in two places on sheet "nav"

6) in the corresponding filename which the "nav" sheet will point to, e.g.
"investigate.html"

7) in many places in each template (NOTE: these can be replaced with a search-replace function): 
- where the template references the spreadsheet you changed earlier, should look something like "{% set investigate = 2 %}" for the first occurrence
- optionally, could change the id assigned to a certain div element, which comes from this name
- for the next two occurrences, should look like and like "stages[investigate]"
- next two occurrences in references to the markdown content, should look like something like 'read_file("content/investigate.md")'

8) In the markdown content filenames

9) In the chart, which has a name for each stage

I believe that's all the references you have to change, to be consistent.
(All this in the name of not prematurely optimizing. Can we optimize yet?)

On Sat, Feb 15, 2014 at 2:10 AM, Wilberto Morales
notifications@github.comwrote:

> On the investigate tab? Including the chart? This can be changed easily.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/57#issuecomment-35150010
> .

## 

Brian Peterson
