### ISSUE TITLE
Change graphic to be more clear

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#59]
Looking at the awesome current graphic on our website, which @sarahelizabeth created...

![](http://i.imgur.com/aeJxCTw.png)

...it's unfortunately difficult to interpret what it means, so much so that I suspect it may inaccurately portray our data. 

The main reason I think this is so is that our group agreed to 3 main categories: 
- Available,
- FOIA-able, and
- Not Available 

But there are at least 4 categories represented with the image: 
- Black,
- Grey,
- Red, and
- Nothing

What do we think is going on?

**Comment by sarahelizabeth** [comment]
I haven't created a key yet, I'm sorry. I am working on it. Black means a lot gray means some and red means a little.

**Comment by bepetersn** [comment]
What does nothing mean?

**Comment by sarahelizabeth** [comment]
It means nothing. It means there is no data that is available in that format.

**Comment by bepetersn** [comment]
That ... I don't know if I understand.

**Comment by GovInTrenches** [comment]
Can we have icons to correspond? Check marks for completely open, F for FOIA'able and an X for nothing at all. That way even if the colors arnt intuitive it'll still make sense

Christopher Whitaker
(Sent from iPhone)

**Comment by sarahelizabeth** [comment]
But that would be redundant. The top row already specifies the three types
of data: "Open Data", "FOIA-able Data", and "Unavailable Data" (I can make
that more clear). The dots signify the _amount_ of each type of data
(namely, a lot, some, none). If there is nothing I can include a black
circle. Does that make more sense?

**Comment by GovInTrenches** [comment]
Redundancy isn't a bad thing per se. To me a color scheme like "red yellow green" makes sense because that's what we're used to. If we don't use that - then I'd like icons just so that there's zero confusion. 

Christopher Whitaker
(Sent from iPhone)

**Comment by sarahelizabeth** [comment]
Does this make any more sense to you? Where the bigger the circle the more
data is available in that category?

 Screen Shot 2014-02-07 at 8.33.56
PM.pnghttps://docs.google.com/file/d/0B9IgbhrbjJC_YlZKSmtPU1pGb2M2WXNHM1RCS00tbkJZRTJz/edit?usp=drive_web

**Comment by GovInTrenches** [comment]
MUCCCCH better. Now that makes more sense. 

Thanks! 

-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On February 12, 2014 at 7:29:22 PM, Sarah Murray (notifications@github.com) wrote:

Does this make any more sense to you? Where the bigger the circle the more
data is available in that category?

Screen Shot 2014-02-07 at 8.33.56
PM.pnghttps://docs.google.com/file/d/0B9IgbhrbjJC_YlZKSmtPU1pGb2M2WXNHM1RCS00tbkJZRTJz/edit?usp=drive_web

**Comment by sarahelizabeth** [comment]
Super, I will fix it now.

**Comment by sarahelizabeth** [comment]
How does that look?
@bepetersn @GovInTrenches @eads

**Comment by sarahelizabeth** [comment]
![screen shot 2014-02-12 at 8 10 29 pm](https://f.cloud.github.com/assets/4665373/2156124/10168cca-9454-11e3-8c86-548530f34b27.png)

**Comment by GovInTrenches** [comment]
Looks good to me - We may change the labels on the nav bar (which would change this graphic) - but I like the way this looks. Thanks for getting to this so quickly!

**Comment by sarahelizabeth** [comment]
No problem. I made a little key, I am just figuring out where I want to put
it.

**Comment by bepetersn** [comment]
Hey Sarah,

If you look at what your chart is saying, the colors and the categories are
out of sync and/or redundant. For instance, the "Not Available / Report"
item of your table tells us that there is "very little" data that is not
available--but this circle is colored red! Isn't very little unavailable
data in fact positive? And if you look at the table item "Not Available /
Prosecution", the acknowledged worst fact that our project is trying to
highlight is being downplayed, by associating no color with it.

In another words, whether something is bad or not, and the resultant
connotation we ought to imply with our design is not just dependent on "how
much" for that category, but, in effect, "how much" multiplied by the
category you're describing. To visualize this, the proper color
representation of this (irrespective of design effectiveness for the
moment) is to color the entire "Not Available" row red, the entire
"FOIA-able" row grey, and the entire "Available" row black.

Considering all of this, I think one solution in this case might be to go
back to using size of circle to represent how much of a given category
exists for a stage. We could keep the three colors, but just color each
circle in a column black, red, and grey respectively, if that is clear.
This might look strange. It might work better to flip the axes of the chart.

I can draw out my thoughts if that would help.

**Comment by bepetersn** [comment]
Wowwww, just saw that you had a lot of correspondence that I missed. Um,
for the moment, disregard everything I just said.

On Wed, Feb 12, 2014 at 9:15 PM, Brian Peterson bepetersn@gmail.com wrote:

> Hey Sarah,
> 
> If you look at what your chart is saying, the colors and the categories
> are out of sync and/or redundant. For instance, the "Not Available /
> Report" item of your table tells us that there is "very little" data that
> is not available--but this circle is colored red! Isn't very little
> unavailable data in fact positive? And if you look at the table item "Not
> Available / Prosecution", the acknowledged worst fact that our project is
> trying to highlight is being downplayed, by associating no color with it.
> 
> In another words, whether something is bad or not, and the resultant
> connotation we ought to imply with our design is not just dependent on "how
> much" for that category, but, in effect, "how much" multiplied by the
> category you're describing. To visualize this, the proper color
> representation of this (irrespective of design effectiveness for the
> moment) is to color the entire "Not Available" row red, the entire
> "FOIA-able" row grey, and the entire "Available" row black.
> 
> Considering all of this, I think one solution in this case might be to go
> back to using size of circle to represent how much of a given category
> exists for a stage. We could keep the three colors, but just color each
> circle in a column black, red, and grey respectively, if that is clear.
> This might look strange. It might work better to flip the axes of the chart.
> 
> I can draw out my thoughts if that would help.
> 
> On Feb 12, 2014 6:03 PM, "Sarah Murray" notifications@github.com wrote:
> 
>  I haven't created a key yet, I'm sorry. I am working on it. Black means a
> 
> > lot gray means some and red means a little.
> > 
> > > On Feb 12, 2014, at 4:34 PM, Brian Everett Peterson <
> > > notifications@github.com> wrote:
> > > 
> > > Looking at the awesome current graphic on our website, which
> > > @sarahelizabeth created...
> > > 
> > > ...it's unfortunately difficult to interpret what it means, so much so
> > > that I suspect it may inaccurately portray our data.
> > > 
> > > The main reason I think this is so is that our group agreed to 3 main
> > > categories:
> > > 
> > > Available,
> > > FOIA-able, and
> > > Not Available
> > > But there are at least 4 categories represented with the image:
> > > 
> > > Black,
> > > Grey,
> > > Red, and
> > > Nothing
> > > What do we think is going on?
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/59#issuecomment-34933944
> > .

## 

Brian Peterson

**Comment by bepetersn** [comment]
I see. I like how this new graphic looks a lot. The simplicity of it is
very appealing, compared to having different colors all over the place.

If you wanted to still use colors to convey "badness" of a particular
circle, (in addition to circle size; thus achieving slightly more
redundancy, in the positive sense Chris was thinking above), you could do
what the last two paragraphs of my two-emails-ago response suggests.

On Wed, Feb 12, 2014 at 9:17 PM, Brian Peterson bepetersn@gmail.com wrote:

> Wowwww, just saw that you had a lot of correspondence that I missed. Um,
> for the moment, disregard everything I just said.
> 
> On Wed, Feb 12, 2014 at 9:15 PM, Brian Peterson bepetersn@gmail.comwrote:
> 
> > Hey Sarah,
> > 
> > If you look at what your chart is saying, the colors and the categories
> > are out of sync and/or redundant. For instance, the "Not Available /
> > Report" item of your table tells us that there is "very little" data that
> > is not available--but this circle is colored red! Isn't very little
> > unavailable data in fact positive? And if you look at the table item "Not
> > Available / Prosecution", the acknowledged worst fact that our project is
> > trying to highlight is being downplayed, by associating no color with it.
> > 
> > In another words, whether something is bad or not, and the resultant
> > connotation we ought to imply with our design is not just dependent on "how
> > much" for that category, but, in effect, "how much" multiplied by the
> > category you're describing. To visualize this, the proper color
> > representation of this (irrespective of design effectiveness for the
> > moment) is to color the entire "Not Available" row red, the entire
> > "FOIA-able" row grey, and the entire "Available" row black.
> > 
> > Considering all of this, I think one solution in this case might be to go
> > back to using size of circle to represent how much of a given category
> > exists for a stage. We could keep the three colors, but just color each
> > circle in a column black, red, and grey respectively, if that is clear.
> > This might look strange. It might work better to flip the axes of the chart.
> > 
> > I can draw out my thoughts if that would help.
> > 
> > On Feb 12, 2014 6:03 PM, "Sarah Murray" notifications@github.com wrote:
> > 
> >  I haven't created a key yet, I'm sorry. I am working on it. Black means
> > 
> > > a lot gray means some and red means a little.
> > > 
> > > > On Feb 12, 2014, at 4:34 PM, Brian Everett Peterson <
> > > > notifications@github.com> wrote:
> > > > 
> > > > Looking at the awesome current graphic on our website, which
> > > > @sarahelizabeth created...
> > > > 
> > > > ...it's unfortunately difficult to interpret what it means, so much so
> > > > that I suspect it may inaccurately portray our data.
> > > > 
> > > > The main reason I think this is so is that our group agreed to 3 main
> > > > categories:
> > > > 
> > > > Available,
> > > > FOIA-able, and
> > > > Not Available
> > > > But there are at least 4 categories represented with the image:
> > > > 
> > > > Black,
> > > > Grey,
> > > > Red, and
> > > > Nothing
> > > > What do we think is going on?
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/59#issuecomment-34933944
> > > .
> 
> ## 
> 
> Brian Peterson

## 

Brian Peterson

**Comment by bepetersn** [comment]
Sorry for so many emails.

On Wed, Feb 12, 2014 at 9:23 PM, Brian Peterson bepetersn@gmail.com wrote:

> I see. I like how this new graphic looks a lot. The simplicity of it is
> very appealing, compared to having different colors all over the place.
> 
> If you wanted to still use colors to convey "badness" of a particular
> circle, (in addition to circle size; thus achieving slightly more
> redundancy, in the positive sense Chris was thinking above), you could do
> what the last two paragraphs of my two-emails-ago response suggests.
> 
> On Wed, Feb 12, 2014 at 9:17 PM, Brian Peterson bepetersn@gmail.comwrote:
> 
> > Wowwww, just saw that you had a lot of correspondence that I missed. Um,
> > for the moment, disregard everything I just said.
> > 
> > On Wed, Feb 12, 2014 at 9:15 PM, Brian Peterson bepetersn@gmail.comwrote:
> > 
> > > Hey Sarah,
> > > 
> > > If you look at what your chart is saying, the colors and the categories
> > > are out of sync and/or redundant. For instance, the "Not Available /
> > > Report" item of your table tells us that there is "very little" data that
> > > is not available--but this circle is colored red! Isn't very little
> > > unavailable data in fact positive? And if you look at the table item "Not
> > > Available / Prosecution", the acknowledged worst fact that our project is
> > > trying to highlight is being downplayed, by associating no color with it.
> > > 
> > > In another words, whether something is bad or not, and the resultant
> > > connotation we ought to imply with our design is not just dependent on "how
> > > much" for that category, but, in effect, "how much" multiplied by the
> > > category you're describing. To visualize this, the proper color
> > > representation of this (irrespective of design effectiveness for the
> > > moment) is to color the entire "Not Available" row red, the entire
> > > "FOIA-able" row grey, and the entire "Available" row black.
> > > 
> > > Considering all of this, I think one solution in this case might be to
> > > go back to using size of circle to represent how much of a given category
> > > exists for a stage. We could keep the three colors, but just color each
> > > circle in a column black, red, and grey respectively, if that is clear.
> > > This might look strange. It might work better to flip the axes of the chart.
> > > 
> > > I can draw out my thoughts if that would help.
> > > 
> > > On Feb 12, 2014 6:03 PM, "Sarah Murray" notifications@github.com
> > > wrote:
> > > 
> > >  I haven't created a key yet, I'm sorry. I am working on it. Black means
> > > 
> > > > a lot gray means some and red means a little.
> > > > 
> > > > > On Feb 12, 2014, at 4:34 PM, Brian Everett Peterson <
> > > > > notifications@github.com> wrote:
> > > > > 
> > > > > Looking at the awesome current graphic on our website, which
> > > > > @sarahelizabeth created...
> > > > > 
> > > > > ...it's unfortunately difficult to interpret what it means, so much
> > > > > so that I suspect it may inaccurately portray our data.
> > > > > 
> > > > > The main reason I think this is so is that our group agreed to 3 main
> > > > > categories:
> > > > > 
> > > > > Available,
> > > > > FOIA-able, and
> > > > > Not Available
> > > > > But there are at least 4 categories represented with the image:
> > > > > 
> > > > > Black,
> > > > > Grey,
> > > > > Red, and
> > > > > Nothing
> > > > > What do we think is going on?
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/59#issuecomment-34933944
> > > > .
> > 
> > ## 
> > 
> > Brian Peterson
> 
> ## 
> 
> Brian Peterson

## 

Brian Peterson

**Comment by sarahelizabeth** [comment]
I am going to close this issue and if we show it to a lot of people and
they don't get it, then I will reopen it, is that ok? I have shown it to
several people who were able to grasp the concept with very little
explanation.

**Comment by bepetersn** [comment]
Yep, I was gonna close it myself.
