### ISSUE TITLE
Finish adding data fields for court and jail pages

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#62]
We need to add to the markdown files:
- court conviction data fields,
- jail data fields

More importantly, we need to color in all of the fields in our markdown files.

**Comment by sarahelizabeth** [comment]
@bepetersn I added all the colors (as per Tracy's Justice Data 3.0 doc) to the available datasets (found in Report and Investigate) using span tags

**Comment by bepetersn** [comment]
Thanks a lot, Sarah. Sorry for all that writing in the other thread... my
phone ran out of battery awhile ago, and I just remembered to check back in
with the conversation. After previewing the site with your graphic, I think
it's by far the best way to do it.

How do you feel about how the colored data fields look?

On Wed, Feb 12, 2014 at 8:53 PM, Sarah Murray notifications@github.comwrote:

> @bepetersn https://github.com/bepetersn I added all the colors (as per
> Tracy's Justice Data 3.0 doc) to the available datasets (found in Report
> and Investigate) using span tags
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/62#issuecomment-34943643
> .

## 

Brian Peterson

**Comment by bepetersn** [comment]
I can get the other datasets in there.

**Comment by sarahelizabeth** [comment]
No problem. I think the coloration is good. Explanatory without distracting
from the information. I'm happy with the way this is progressing.

**Comment by bepetersn** [comment]
Court Conviction data which needs to be added can be found at:

https://drive.google.com/file/d/0B6oKGQl-UtL7Q3RZV3hLbWJWVXJVVE9fUGl3eElCVU1yMkN3/edit?usp=sharing

**Comment by bepetersn** [comment]
Jail data from the Cook County Sheriff's Office, which needs to be added, can be found here:

https://drive.google.com/file/d/0B6oKGQl-UtL7WkVSemhZZENKbHM/edit?usp=sharing

**Comment by bepetersn** [comment]
Hey @wilbertom or other interested parties, this data can now be uploaded by someone other than me! Been meaning to put it on the site forever, but haven't gotten around to it. Sorry the one is in PDF format...

**Comment by sarahelizabeth** [comment]
Would you rather have me do this or change the site nav?

**Comment by bepetersn** [comment]
Definitely site nav, only you can do that

**Comment by bepetersn** [comment]
Just put up the Court Conviction Data. Now, all the data fields that have been provided to me by Tracy, any that I know about, are up on the site.
