### ISSUE TITLE
Need more, better images

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#65]
I know this is a recurring thing for our group, but I feel some of our current photos are less than wonderful, simply because they don't let us see people and especially their faces. 

Also, because we're planning to add more tabs to the site, we're inevitably going to need more photos.

**Comment by bepetersn** [comment]
@GovInTrenches, would you be able to post the link to that folder of yours that contains all the photos we have access to? I know it's somewhere in a long chain of emails, just would make it easier to have here.

**Comment by GovInTrenches** [comment]
I use Flickr for all of my pictures - Dan has a ton of them 

http://www.flickr.com/search/?q=Chicago+Police&l=cc&ss=0&ct=0&mt=photos&w=all&adv=1

**Comment by bepetersn** [comment]
Maria found at least one photo for all of our pages, which are all up on the site now. Maybe all of them won't stick--I think the Prison one at least is pretty great.
