### ISSUE TITLE
make site look a lot better on mobile

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#67]
Because we're using bootstrap frames, the grunt's work of getting most everything to show up on the page, whether in mobile or web view, is already done. However, there's still probably a lot of optimization to be done.

**Comment by wilbertom** [comment]
Overall the content scales pretty good. Just a few issues.
1. The navigation bar becomes nearly unusable and doesn't look as it should.
2. The title follows you down as you scroll in a nearly invisible color.
3. The titles and some other content overflow.

Here are some tricks I have picked up for mobile driven development.
1. Resize the browser down to a small size
2. On Mac OS X I have a `simulator` script:

```
#!/bin/bash

open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app

```
1. For my Linux warriors the [opera simulator is a good choice](http://www.opera.com/developer/mobile-emulator)

**Comment by wilbertom** [comment]
And testing on the [firefox os emulator](https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/) wouldn't hurt neither.
