### ISSUE TITLE
can't get pictures to show up on the production site!

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#81]
I can't understand why this is happening. I just published to the site. Now my browser shows our server throwing 404 error messages on each page. None of the pictures show up. This is despite the fact that I have all the pictures in my local, and `tarbell publish` thinks the server is up-to-date with what's in my repository.

Can anyone confirm the pictures are missing, that it's not just me? Perhaps we can ask someone on the tech side at smartchicago what files they can see on the server.

**Comment by GovInTrenches** [comment]
I can't see the pictures - @srobbin, can you see the files?

**Comment by srobbin** [comment]
The pages are referring to `index.jpg` as being in the root directory, when it's in `img` directory. I don't have a ton of Tarbell experience, but my guess is that you either need to prepend `img/` before you `featured_image` tags, or reference `img` in the content field.

**Comment by eads** [comment]
Sounds like Scott's got the right idea.

All links (in-site page links, img srcs, style hrefs, etc) should be
relative to the current directory. Either option proposed by Scott is fine.

On Tue, Feb 18, 2014 at 11:13 AM, Scott Robbin notifications@github.comwrote:

> The pages are referring to index.jpg as being in the root directory, when
> it's in img. I don't have a ton of Tarbell experience, but my guess is
> that you either need to prepend img/ before you featured_image tags, or
> reference img in the content field.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/81#issuecomment-35407993
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by bepetersn** [comment]
I can see what Scott's saying that images are being referenced as if in project root. I'll try including a reference to the 'img' directory. What I don't understand is why the images get discovered correctly in my local no matter what. I'm about to try re-publishing again without any proof that it will work.

**Comment by bepetersn** [comment]
I'm missing something. "Call for Service", "Incidents" and Arrest pages now have images; home page doesn't have its index.jpg

**Comment by bepetersn** [comment]
K, got everything fixed. Had a few latent bugs. This must've happened because we re-engineered the spreadsheet used to store the image names awhile back, didn't include the img directory. Then I also didn't publish for awhile, and forgot what could have been causing it.

Thanks @srobbin, @GovInTrenches
