### ISSUE TITLE
fit flowchart on page

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#84]
There's not necessarily one best way to do this, but @sarahelizabeth is trying to make a rather (horizonally) large flowchart for our home page of the whole chicago justice system, to tie the site together. 

Part of making this possible might be a feature to zoom in on the image.

**Comment by bepetersn** [comment]
So this is might look stupid / old, but would any of these or similar "zoom" solutions be useful for our purposes, @sarahelizabeth?

http://www.mind-projects.it/projects/jqzoom/demos.php#demo1

**Comment by bepetersn** [comment]
How about this utility? It seems closer to what we want.

http://epicserve.github.io/jquery-photo-enlarger/

**Comment by sarahelizabeth** [comment]
Yes, I like the second one.

**Comment by eads** [comment]
How was the flowchart image generated? You might be able to use SVG.

On Fri, Feb 21, 2014 at 10:36 AM, Sarah Murray notifications@github.comwrote:

> Yes, I like the second one.
> 
> On Thu, Feb 20, 2014 at 7:19 PM, Brian Everett Peterson <
> notifications@github.com> wrote:
> 
> > How about this utility? It seems closer to what we want.
> > 
> > http://epicserve.github.io/jquery-photo-enlarger/
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/chicago-justice/issues/84#issuecomment-35689701>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/84#issuecomment-35747473
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by sarahelizabeth** [comment]
I haven't finished it yet because no one can understand anything I do and
every time I try to make something it is apparently fundamentally wrong on
some level. But I'm making it in illustrator.

**Comment by bepetersn** [comment]
Yeah, I was just preemptively trying to think how to fit it on a page. Another option, perhaps yet better: http://fancybox.net/

I'm having difficulty getting a sense for whether SVG images are also manipulable with JQuery. Perhaps not. Looks like you have to use a separate svg-manipulation js library.

**Comment by bepetersn** [comment]
I'm waiting until @sarahelizabeth has done her best to put together the flowchart, to see if this issue is going to be closed, but we probably won't need to "zoom in" on the flowchart, or ideally anyway.

**Comment by sarahelizabeth** [comment]
I was going to show you guys tonight, but this is what I did. Image is
attached.

**Comment by bepetersn** [comment]
Hey Sarah, I don't see the image.
