### ISSUE TITLE
research / figure out how to responsivize "black hole" 

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#85]
On the "Prosecute" page, the primary image right now is in fact not an image, but just a circle I created. Somehow, by some means, it needs to be responsivized for different screen sizes, obviously for mobile, but it even starts to look bad on some smaller laptops.

In other words, it was a placeholder that I designed to fit on my own screen. Somehow, it needs to become a little bit more. @eads, @wilbertom, your help / attention / suggestions would be appreciated.

**Comment by bepetersn** [comment]
@eads unearthed this gem: http://www.mademyday.de/css-height-equals-width-with-pure-css.html

**Comment by sarahelizabeth** [comment]
Are we sure that we still want to use this? I think a photo would be more consistent/less weird. I really don't think anyone is going to get it.

**Comment by bepetersn** [comment]
I agree. I want a picture. Even one of an empty court room in Chicago would feel better.

**Comment by bepetersn** [comment]
http://www.flickr.com/photos/usachicago/3879627035/in/photolist-6UQ6Xi-6UQigi-73CKzJ-bWgTmF-jpXf7v-acDLKW-8AfhiJ-ej43wS-e7xaQ1-e7xaH5-e7runz-dRYZb9-dRMnEX-dRTnYP-dRTnYe-eUbXRE-dRT6pL-dRMv9e-dRTnZF-dRTo36-dRYZgQ-dRTo2e-dRSXMb-eUbNSQ-brytnc-bzqs8n-8z5B6E-8z2vuT-d9ZufX-8i2NUt-9WvJwk-aFi3U8-a6ATRj-aV7n5K-bSdFnp-9b1ZA2-8tPych-geQTBP-bG6yye-8kX4tE-eZayEr-eZayPT-dgQW5Y-bUKq3R-cemMrS-cnKiyY-eTZqbK-eUbXPC-eTZpC6-eUbYbb-m1Mk6Z/

**Comment by bepetersn** [comment]
Thoughts, @GovInTrenches?

**Comment by eads** [comment]
Use an image.

**Comment by GovInTrenches** [comment]
I like the image you picked out Brian - lets go with it
-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On March 13, 2014 at 9:20:23 PM, David Eads (notifications@github.com) wrote:

Use an image.

**Comment by bepetersn** [comment]
Tangentially related question, while I have everyone's attention:

What should go in the captions for these photos? A short explanation of
what's going on, or just photographer?

**Comment by GovInTrenches** [comment]
Just the photographer I think 
-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On March 13, 2014 at 9:25:27 PM, Brian Everett Peterson (notifications@github.com) wrote:

Tangentially related question, while I have everyone's attention:

What should go in the captions for these photos? A short explanation of
what's going on, or just photographer?

**Comment by sarahelizabeth** [comment]
There is now a section in the stages page of the google doc called
"image_caption" where credits can be placed.

**Comment by bepetersn** [comment]
Nice! Good idea.

**Comment by sarahelizabeth** [comment]
I am going to close this since we are using a picture.
