### ISSUE TITLE
do custom crop on some images for smaller viewports

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#98]
Some pictures with prominent faces, in particular, need to have custom crops of their respective photos for smaller viewports. 

For instance, the home page has a picture of a policemen on it. After lower than about 630px in browser width, and viewport lower than about 560px, the face starts to disappear, and the picture is worth a lot less at that point. 

Maybe we should get rid of the picture at this small width, I'm not sure. This is not as big as issue for almost any other image, most don't have as centered a focus.

**Comment by sarahelizabeth** [comment]
Done. Aligned the index page and the Prison page.
